### ISSUE TITLE
Odd elvish day behaviour

### ISSUE THREAD

**Issue by horus1963** [joaquingatica/Notie-Imberisseo#2]
I noticed an odd behaviour.

If you entered March 26, 2016 before sunset your will get Elenya, Mettarë, XIV 143 then when you advance one day to March 27, 2016 before sunset you get Valanya, Yestarë, XIV 144.

Why did the day jump from Elenya to Valanya, shouldn’t it be Anarya?

**Comment by joaquingatica** [comment]
@horus1963 Had abandoned this project for a while, but I'm back now and fixed this issue. It's included in release [2.5.1](https://github.com/joaquingatica/Notie-Imberisseo/releases/tag/v2.5.1).

The original days of the week were wrong, my apologies. March 26, 2016 had to be actually Aldúya. Now it's working correctly, and after sunset/March 27, it's the next week day which is Menelya.

Thanks for the feedback, it was really valuable

**Comment by horus1963** [comment]
Dear Joaquin,

Thank you very much for fixing this. I have downloaded the new version and have one note. I am here in Mississauga, Ontario in Canada. I am noticed an odd part in that it believes that the software believes that we are after sunset as it states that sunset is at 09:18 when actually it is at 17:31 (see attached window shot).

Again thanks for looking into this.

Best regards
Hesham

**Comment by joaquingatica** [comment]
@horus1963 Thanks for this! I think I noticed it as well, but wasn't entirely sure, thanks for confirming. I'll take a look at it, would you mind creating a new issue in GithHub for this? That way you'll be notified when there's progress.

**Comment by horus1963** [comment]
Done.

Thanks
Hesham
