### ISSUE TITLE
Incorrect sunset detection

### ISSUE THREAD

**Issue by horus1963** [joaquingatica/Notie-Imberisseo#4]
Dear Joaquin,

I have downloaded the new version (2.5.1) and have one note. I am here in Mississauga, Ontario in Canada. I noticed an odd part in that the software believes that we are after sunset as it states that sunset is at 09:18 when actually it is at 17:35. It is now 10:20.

Thanks for looking into this.
<img width="600" alt="screen shot 2017-02-02 at 9 57 54 am" src="https://cloud.githubusercontent.com/assets/11258233/22555346/6cf136c2-e931-11e6-843e-85d10fbdb150.png">

**Comment by joaquingatica** [comment]
@horus1963 Thanks, I'm on it!

**Comment by joaquingatica** [comment]
@horus1963 Fixed, will be included in next release.
