### ISSUE TITLE
Day of week no longer matches quenya101.com

### ISSUE THREAD

**Issue by horus1963** [joaquingatica/Notie-Imberisseo#5]
Dear Joaquin,

With the new version (2.5.1) I noticed that the results are no longer matching any of the weekdays of the dates on quenya101 (https://quenya101.com/calendar/my-special-day-in-the-elvish-calendar/) when previously it used to match them for dates 2015 and older. 

Does this mean that the days on quneya101.com are incorrect and needs to be changed or another visit to the app is needed?

Thanks

**Comment by joaquingatica** [comment]
@horus1963 I noticed that, and sent the latest version for Erunno to review. For him to tell me if I need to revise, or the website needs to be revised. I'll keep you posted.

**Comment by joaquingatica** [comment]
@horus1963 Correctness verified by Erunno, and he'll be revising the dates in the website.

Stable version [3.0.0](https://github.com/joaquingatica/notie-imberisseo/releases/tag/v3.0.0) released.
